### ISSUE TITLE
Replace acronym error

### ISSUE THREAD

**Issue by thoppe** [NIHOPA/NLPre#64] opened 2017-05-24 14:07 UTC
Somehow, the combination of these two sentences causes the parser to fail here. Taking away either one will allow it to run.

``` python
text = '''
A large region upstream (~30 kb) of GATA 4.
Small interfering RNA (siRNA) mediated depletion of EZH2.
'''

from nlpre import replace_acronyms as parser
print parser({})(text)
```
```
Traceback (most recent call last):
  File "tx.py", line 15, in <module>
    print parser({})(text)
  File "/usr/local/lib/python2.7/dist-packages/nlpre/replace_acronyms.py", line 200, in __call__
    doc_counter = self.IPP(document)
  File "/usr/local/lib/python2.7/dist-packages/nlpre/identify_parenthetical_phrases.py", line 41, in __call__
    subtokens = self._check_matching(word, k, tokens)
  File "/usr/local/lib/python2.7/dist-packages/nlpre/identify_parenthetical_phrases.py", line 129, in _check_matching
    if let not in tokens_to_remove]
TypeError: 'str' object is not callable
```

**Comment by HarryBaker** [comment] 2017-05-26 16:42
I have a fix to prevent it from crashing. 

However, the code doesn't recognize that siRNA is an acronym for Small interfering RNA. It expects every letter in the acronym to have a corresponding word in the preceding phrase. Do you think this will be a common enough issue to write code to recognize?

**Comment by thoppe** [comment] 2017-05-26 17:15
What was the cause of the crash? Can you post a PR so I can look it over?

The siRNA is indeed a special case -- we will have to look at it later to see if it's worth it.

**Comment by HarryBaker** [comment] 2017-05-26 17:35
The cause of the crash is that in identify_parenthetical phrases, the code tries to recognize a phrase by iterating from the acronym backwards through the document, until it reaches the end of the document. For each word, it grabs the capitalized first letter, and tries to reverse engineer the acronym. If there's a match, then it is identified as a phrase. The issue is that during the iteration, if the code hits a parenthesis ParseObject, it fails when trying to capitalize it. My fix is to only try to grab the first word if it is a base string 

We should probably split on sentences, so it only has to iterate backwards through the sentence rather than the entire document. That, or implement a heuristic of when it can stop iterating. (2x-3x the length of the acronym seems like it would be a good stopping point).

**Comment by thoppe** [comment] 2017-05-26 17:55
I like the heuristic idea, since punctuation can be tricky with acronyms (I've seen plenty with a period, colon or slash). At most 2x, stopping at the start of the string, is a good stopping point I think.

**Comment by thoppe** [comment] 2017-05-26 18:20
You probably shouldn't name tests after me either :frowning: 

How about using the name that describes the problem? I'll fix it and merge it in.

**Comment by HarryBaker** [comment] 2017-05-26 18:26
i have them renamed in another branch, i was gonna do a pull request after this one was merged.

**Comment by thoppe** [comment] 2017-05-26 18:29
No worries. I have it fixed. Once a PR is out, that's what we can focus on -- if there is something wrong with it, it won't be obvious that the fix is in another branch.

**Comment by thoppe** [comment] 2017-06-01 14:13
This is still a problem. This error looks to be coming from the same source:

``` python
text='''In Drosophila, the CK2 kinase phosphorylates and destabilizes the PERIOD (PER) and TIMELESS (TIM) proteins, which inhibit CLOCK (CLK) transcriptional activity.'''
ABBR = identify_parenthetical_phrases()(text)
print ABBR
```

```
Traceback (most recent call last):
  File "tx.py", line 7, in <module>
    ABBR = identify_parenthetical_phrases()(text)
  File "/home/hoppeta/git-repo/NLPre/nlpre/identify_parenthetical_phrases.py", line 41, in __call__
    subtokens = self._check_matching(word, k, tokens)
  File "/home/hoppeta/git-repo/NLPre/nlpre/identify_parenthetical_phrases.py", line 100, in _check_matching
    subtoken_let = [let.upper()[0] for let in subtokens]
TypeError: 'str' object is not callable
```

**Closed** 2017-06-01 20:42 UTC
Labels: bug
